version: '3.2'
services:
  metrics-bridge:
    image: openjdk:alpine
    volumes:
      - ./:/usr/src/myapp
    working_dir: /usr/src/myapp
    command: /bin/sh -c "./gradlew clean shadowJar && java -jar ./build/libs/metrics-bridge-*-all.jar -c config.json"
    restart: unless-stopped
